### ISSUE TITLE
No messages after collector config

### ISSUE THREAD

**Issue by yarnping** [graylog-labs/collector#95]
hello~
I was follow the doc:
[http://docs.graylog.org/en/2.2/pages/collector_sidecar.html](url)
collector shows ```Running``` but no messages on web interface.
then run debug with ```graylog-collector-sidecar -debug -c /etc/graylog/collector-sidecar/collector_sidecar.yml```
always shows:

> DEBU[0915] [RequestConfiguration] No configuration update available, skipping update. 
DEBU[0925] [RequestConfiguration] No configuration update available, skipping update. 
DEBU[0935] [RequestConfiguration] No configuration update available, skipping update. 
DEBU[0945] [RequestConfiguration] No configuration update available, skipping update. 
DEBU[0955] [RequestConfiguration] No configuration update available, skipping update. 
DEBU[0965] [RequestConfiguration] No configuration update available, skipping update. 
DEBU[0975] [RequestConfiguration] No configuration update available, skipping update. 

something wrong?

**Comment by mariussturm** [comment]
Hi,
what you see is a debug message, so no reason to worry.

If you don't see  any messages in the web interface
  * review your collector configuration if you are collecting the right files
  * and if there is a proper Graylog input configured so that the collector can send messages to the right endpoint.
  * check the log files of the collector (nxlog/filebeat) for any error messages
